//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeSensusApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tree_Sensus_Report_DBEntities1 : DbContext
    {
        public Tree_Sensus_Report_DBEntities1()
            : base("name=Tree_Sensus_Report_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_User_Details> tbl_User_Details { get; set; }
        public virtual DbSet<tbl_Tree_Details> tbl_Tree_Details { get; set; }
    }
}
