//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeSensusApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tree_Details
    {
        public int details_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> ward_no { get; set; }
        public string tree_species { get; set; }
        public string photo { get; set; }
        public string local_name { get; set; }
        public string lattitude { get; set; }
        public string longitude { get; set; }
        public Nullable<int> height_in_feet { get; set; }
        public Nullable<int> canopy_in_feet { get; set; }
        public Nullable<int> avg_tree_age { get; set; }
        public string tree_status { get; set; }
        public string ownership { get; set; }
        public string owner_name { get; set; }
        public string owner_contact { get; set; }
        public Nullable<int> num_of_tree { get; set; }
    
        public virtual tbl_User_Details tbl_User_Details { get; set; }
    }
}
